
all:
	dot -Tpng -O adesk-server.dot
	dot -Tpng -O adesk-db.dot
	dot -Tpng -O adesk-arch.dot
	dot -Tpng -O adesk-nav.dot
	dot -Tpng -O adesk-rest.dot
	dot -Tpng -O adesk-file.dot
	dot -Tpng -O adesk-album.dot
	dot -Tpng -O adesk-data.dot
	dot -Tpng -O adesk-useraggr.dot
	circo -Tpng -O adesk-pass.dot
